# this is example. you must replace ccaddress and keys before deploy.

server:
  dsn: "host=localhost user=postgres password=postgres dbname=concurrent port=5432 sslmode=disable"
  redisAddr: "localhost:6379"

concurrent:
  fqdn: changeme.example.tld
  ccaddr: CCxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  publickey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  privatekey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  admins:
    - CCxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

nodeinfo:
  openRegistrations: true
  metadata:
    nodeName: concurrent
    nodeDescription: concurrent activitypub integration
    maintainer:
      name: notset
      email: notset@example.com
    themeColor: '#20193b'

