name: Test

on:
  push:
    branches:
      - "master"
      - "develop"
  pull_request:
    branches: 
      - "master"
      - "develop"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.20.4
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Go Generate
      run: go generate ./...

    - name: Run tests with coverage
      run: go test -coverprofile=coverage.out ./...

    - name: Set custom env var
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
        elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "BRANCH_NAME=pr-${{ github.event.number }}" >> $GITHUB_ENV
        fi

    - name: create dist directory
      run: mkdir -p "dist/$BRANCH_NAME"

    - name: Generate html report
      run : go tool cover -html=coverage.out -o "./dist/$BRANCH_NAME/index.html"

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './dist'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2

